### ISSUE TITLE
Menu Links Not Functioning

### ISSUE THREAD

**Issue by jmf3ig** [WTW-IM/bda-des-sys#20]
- Operating system and version - macOS Mojave 10.14.6
- Browser and version - Chrome latest

The scroll spy right side sub-navigation isn’t functioning on some of the nav elements in the BDA toolkit. For instance, https://wtw-im.github.io/bda-des-sys/base.html#lead-body-copy doesn't render at the anchor tag, it just loads the top of the page.

**Comment by gcolbath** [comment]
This is in the works.

**Comment by gcolbath** [comment]
Fixed.
