### ISSUE TITLE
Accordion Headers Need Style Update

### ISSUE THREAD

**Issue by jmf3ig** [WTW-IM/bda-des-sys#24]
- MacOS 10.14.6
- Chrome latest

Accordion headers are not styled the same as the drawer headers. They should be.
<img width="896" alt="Screenshot 2020-04-10 11 57 04" src="https://user-images.githubusercontent.com/13686427/79131886-305cb000-7d5e-11ea-9140-4b2edd35f151.png">

**Comment by gcolbath** [comment]
Issue has been fixed and deployed.
