### ISSUE TITLE
Update unordered lists styling.

### ISSUE THREAD

**Issue by johnwhitlock** [WTW-IM/bda-des-sys#30]
Context:
https://wtwonline.sharepoint.com/:b:/s/tctnonclient_bdauxvc/ESeDU0dP4MdJgMDOpF4iNvIBU29VgynOL3ND-kw16U4P7A?e=hVm6qo The latest Via Benefits Visual Style Guide includes guidance on square bullets. 

Request:
Please update the toolkit to provide similar guidance, as well as introduce Icons as an option for lists with alternate color choices for both squares and icons.

**Comment by gcolbath** [comment]
This work is mostly done. Just awaiting review, and alignment with forthcoming specs from BAUX.
